// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClassDemoRazorWithDatabase.model;

[Keyless]
public partial class AlkoholView
{
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    public string Name { get; set; }

    public bool Alk { get; set; }
}