// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClassDemoRazorWithDatabase.model;

[Table("Drink")]
public partial class Drink
{
    public Drink():this(0,"",true)
    {
    }

    public Drink(int id, string name, bool alk)
    {
        Id = id;
        Name = name;
        Alk = alk;
    }

    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(25)]
    public string Name { get; set; }

    public bool Alk { get; set; }



    public override string ToString()
    {
        return $"{{{nameof(Id)}={Id.ToString()}, {nameof(Name)}={Name}, {nameof(Alk)}={Alk.ToString()}}}";
    }
}